=== xtender/log4ora/xsd/logmessage.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!--Created with Liquid XML Studio - 30 Day Trial Edition 7.1.1.1206 (http://www.liquid-technologies.com)-->
<xs:schema xmlns="http://log4ora.googlecode.com/svn/trunk/xsd/logmessage.xsd" elementFormDefault="qualified" targetNamespace="http://log4ora.googlecode.com/svn/trunk/xsd/logmessage.xsd" version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="log_message" type="log_message_type" />
  <xs:complexType name="session_info_type">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="1" name="client_ip" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="session_id" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="os_user" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="host" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="client_identifier" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="client_info" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="session_user" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="system_info_type">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="1" name="scn" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="timestamp" type="xs:dateTime" />
      <xs:element minOccurs="1" maxOccurs="1" name="instance" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="db_name" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="message_info_type">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="1" name="log_level" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="log_message" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="exception_info_type">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="1" name="ora_err_number" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="ora_err_message" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="ora_call_stack" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="log_message_type">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="1" name="session_info" type="session_info_type" />
      <xs:element minOccurs="1" maxOccurs="1" name="system_info" type="system_info_type" />
      <xs:element minOccurs="1" maxOccurs="1" name="message_info" type="message_info_type" />
      <xs:element minOccurs="0" maxOccurs="1" name="exception_info" type="exception_info_type" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== xtender/log4ora/trunk/xsd/SampleFile.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio - 30 Day Trial Edition 7.1.1.1206 (http://www.liquid-technologies.com) -->
<log_message xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\log4ora\trunk\xsd\logmessage.xsd">
  <session_info>
    <client_ip>string</client_ip>
    <session_id>string</session_id>
    <os_user>string</os_user>
    <host>string</host>
    <client_info>string</client_info>
    <session_user>string</session_user>
  </session_info>
  <system_info>
    <scn>string</scn>
    <timestamp>string</timestamp>
    <instance>string</instance>
    <db_name>string</db_name>
  </system_info>
  <message_info>
    <log_level>string</log_level>
    <log_message>string</log_message>
  </message_info>
  <exception_info>
    <ora_err_number>string</ora_err_number>
    <ora_err_message>string</ora_err_message>
    <ora_call_stack>string</ora_call_stack>
  </exception_info>
</log_message>
